### ISSUE TITLE
gitlab-jira connection test

### ISSUE THREAD

**Issue by jfrer** [subugoe/tido#126]
In GitLab by @krvoigt on Dec 17, 2020, 14:03

I try to link Jira and Gilab here: https://pm.sub.uni-goettingen.de/browse/EMO-127

**Comment by jfrer** [comment]
In GitLab by @krvoigt on Dec 21, 2020, 10:33

EMO-127

**Comment by jfrer** [comment]
In GitLab by @krvoigt on Dec 21, 2020, 10:54

Dokumentation: Gitlab Jira Verknüfpung
Einstieg: https://docs.gitlab.com/ee/user/project/integrations/jira.html
* Jira Seite
    * https://docs.gitlab.com/ee/user/project/integrations/jira_server_configuration.html
    * create Username: gitlab
    * create Group: gitlab-developers
        * add user to group
    * create Permission Scheme
        * and set link between Group and Permission Scheme
* GitLab Seite
    * https://docs.gitlab.com/ee/user/project/integrations/jira.html#configuring-gitlab
    * https://docs.gitlab.com/ee/user/project/integrations/overview.html#accessing-integrations
        * Projektweise: z.B. digizeit-app (GitLab Repo)
            * Projekt>Zahnrad(links)>Integrations>select: Jira>
            * Enable … (select)
            * Web URL: https://pm.sub.uni-goettingen.de
            * Jira API URL: kein Eintrag
            * Username or Email: gitlab
            * User ist in Jira hinterlegt
            * Enter new Password or API token:
            * aus NLH/GDZ bekanntes SUB-Passwort
            * Transition ID(s): kein Eintrag
            * Jira project key: DINO
            * Test settings
            * Save changes
* Ergänzung der Gitlab Config
    * Use custom settings
    * Enable Jira issues
    * Jira project key: EMO

**Comment by jfrer** [comment]
In GitLab by @krvoigt on Dec 21, 2020, 12:56

AHIK-21

**Comment by mweidling** [comment]
Since TIDO development has switched to GitHub this is probably not relevant anymore.
