### ISSUE TITLE
Make `support` object optional

### ISSUE THREAD

**Issue by jfrer** [subugoe/tido#428]
In GitLab by @tillmann.doenicke on Jan 10, 2024, 11:32

Error shown in TIDO viewer: `support.forEach is not a function`
Assumed cause: The `support` object is optional in the TIDO specification, but required in the TIDO implementation.
Assumed solution: Make The `support` object optional in the TIDO implementation.

**Comment by paulpestov** [comment]
Please check if the error still persists with the latest TIDO version.

**Comment by orlinmalkja** [comment]
@paulpestov i assume it should still persist since in the code we still check support.forEach instead of checking it only when support is defined and is an array
