### ISSUE TITLE
Text panel: marking of bibrefs over several lines

### ISSUE THREAD

**Issue by mokkalicious** [subugoe/tido#468]
Description:
This issue was noticed in Ahiqar project. --> https://projects.academiccloud.de/wp/21804
A complete text passage in the text panel with a biblical reference cannot be marked when it contains more than a line. In such cases, its last line is marked only.

Acceptance criteria:
This issue is done when a complete text passage in the text panel with a biblical reference can be marked.

**Comment by mokkalicious** [comment]
Bei RM in OpenProject am Issue nachgefragt, was hier genau gemacht werden muss.

**Comment by mweidling** [comment]
This is not an TIDO issue since TIDO is already able to highlight several passages of the target of the annotation is set correctly. IMHO this can be closed. @paulpestov
