### ISSUE TITLE
Metadata Panel: Confusing heading for "language" 

### ISSUE THREAD

**Issue by mweidling** [subugoe/tido#525]
On item level, the TextAPI offers information about which languages are present in the given item. These languages are given in form of iso639-3 codes.

The heading for this metadata should be "ISO 639-3 Code" rather than "Language" because it might confuse users which are not familiar with the ISO code.

**Comment by paulpestov** [comment]
Isn't it the other way around? User that are not familiar with ISO codes will be confused by "ISO 639-3 Code"?

**Comment by mweidling** [comment]
No, I don't think so because it's something you can then specifically look up. Some of the ISO values are mildly obscure, e.g. `aai` for Arifama-Miniafia. If the heading is language, I'd expect the latter.

**Comment by mweidling** [comment]
I'm fine with that. :+1:
